In [16]:
import pandas as pd
import os

In [2]:
import pandas as pd

# Load the Excel file and set the second row (index 1) as the header
file_path = "raw/Food Consumption/consumption_g_perday.xlsx"  # Update with your file's location
df = pd.read_excel(file_path, header=2)

# Display the first few rows to verify the data
print(df.head())

C:\Users\bosse\AppData\Local\Programs\Python\Python310\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

  Survey's country  Survey start year  \
0          Austria               2010
1          Austria               2010
2          Austria               2010
3          Austria               2010
4          Austria               2010

                                         Survey name Population Group (L2)  \
0  Austrian Study on Nutritional Status 2010-12 -...                Adults
1  Austrian Study on Nutritional Status 2010-12 -...                Adults
2  Austrian Study on Nutritional Status 2010-12 -...                Adults
3  Austrian Study on Nutritional Status 2010-12 -...                Adults
4  Austrian Study on Nutritional Status 2010-12 -...                Adults

                             Exposure hierarchy (L1)  Number of subjects  \
0                                Alcoholic beverages                 308
1  Animal and vegetable fats and oils and primary...                 308
2                   Coffee, cocoa, tea and infusions                 308
3                                   Composite dishes                 308
4                              Eggs and egg products                 308

   Number of consumers        Mean  Standard Deviation  5th percentile  \
0                  144  149.512987          280.610459             0.0
1                  263   12.737159           11.559832             0.0
2                  282  455.261364          472.676201             0.0
3                  290  237.006981          162.496999             0.0
4                   45    5.064935           14.186542             0.0

   10th percentile      Median  95th percentile  97.5th percentile  \
0         0.000000    0.000000       750.000000         888.322917
1         0.000000   10.122966        31.110981          34.969817
2        60.872340  360.000000      1174.819149        1536.093972
3        44.255862  215.062069       532.407276         590.102241
4         0.000000    0.000000        32.355556          32.500000

   99th percentile Comment
0      1117.673611     NaN
1        38.276099     NaN
2      2244.515248     NaN
3       710.420966     NaN
4        59.740000     NaN

In [3]:
# Drop unwanted columns
columns_to_keep = ['Survey\'s country', 'Survey start year', 'Population Group (L2)', 
                   'Exposure hierarchy (L1)', 'Number of subjects', 'Number of consumers', 'Mean']

df_cleaned = df[columns_to_keep]

In [4]:
df_cleaned

,Survey's country,Survey start year,Population Group (L2),Exposure hierarchy (L1),Number of subjects,Number of consumers,Mean
0,Austria,2010,Adults,Alcoholic beverages,308,144,149.512987
1,Austria,2010,Adults,Animal and vegetable fats and oils and primary...,308,263,12.737159
2,Austria,2010,Adults,"Coffee, cocoa, tea and infusions",308,282,455.261364
3,Austria,2010,Adults,Composite dishes,308,290,237.006981
4,Austria,2010,Adults,Eggs and egg products,308,45,5.064935
...,...,...,...,...,...,...,...
4544,United Kingdom,2011,Toddlers,"Seasoning, sauces and condiments",1314,1030,7.188265
4545,United Kingdom,2011,Toddlers,"Starchy roots or tubers and products thereof, ...",1314,1067,29.264218
4546,United Kingdom,2011,Toddlers,"Sugar and similar, confectionery and water-bas...",1314,797,5.870406
4547,United Kingdom,2011,Toddlers,Vegetables and vegetable products,1314,1188,38.372735
4548,United Kingdom,2011,Toddlers,Water and water-based beverages,1314,1289,256.569757

In [5]:
# Group by country, age group, and food category, then calculate the averages and sums
df_grouped = df_cleaned.groupby(
    ["Survey's country", "Population Group (L2)", "Exposure hierarchy (L1)"], as_index=False
).agg({
    "Mean": "mean",                # Average consumption
    "Number of consumers": "sum",  # Total consumers
    "Number of subjects": "sum"    # Total subjects
})

# Display the grouped DataFrame
df_grouped

,Survey's country,Population Group (L2),Exposure hierarchy (L1),Mean,Number of consumers,Number of subjects
0,Austria,Adolescents,Alcoholic beverages,6.357224,139,811
1,Austria,Adolescents,Animal and vegetable fats and oils and primary...,16.355495,748,811
2,Austria,Adolescents,"Coffee, cocoa, tea and infusions",125.462767,483,811
3,Austria,Adolescents,Composite dishes,59.946303,451,811
4,Austria,Adolescents,Eggs and egg products,16.495834,534,811
...,...,...,...,...,...,...
3285,United Kingdom,Very elderly,"Seasoning, sauces and condiments",20.756175,104,139
3286,United Kingdom,Very elderly,"Starchy roots or tubers and products thereof, ...",79.018675,121,139
3287,United Kingdom,Very elderly,"Sugar and similar, confectionery and water-bas...",20.587659,109,139
3288,United Kingdom,Very elderly,Vegetables and vegetable products,117.874586,130,139
3289,United Kingdom,Very elderly,Water and water-based beverages,569.570063,133,139

In [6]:
# Calculate the percentage of consumers relative to subjects
df_grouped['% Consumers'] = (df_grouped['Number of consumers'] / df_grouped['Number of subjects']) * 100

In [7]:
# Drop the original 'Number of consumers' and 'Number of subjects' columns if no longer needed
df_grouped = df_grouped.drop(columns=['Number of consumers', 'Number of subjects'])

# Display the final DataFrame
df_grouped

,Survey's country,Population Group (L2),Exposure hierarchy (L1),Mean,% Consumers
0,Austria,Adolescents,Alcoholic beverages,6.357224,17.139334
1,Austria,Adolescents,Animal and vegetable fats and oils and primary...,16.355495,92.231813
2,Austria,Adolescents,"Coffee, cocoa, tea and infusions",125.462767,59.556104
3,Austria,Adolescents,Composite dishes,59.946303,55.610358
4,Austria,Adolescents,Eggs and egg products,16.495834,65.844636
...,...,...,...,...,...
3285,United Kingdom,Very elderly,"Seasoning, sauces and condiments",20.756175,74.820144
3286,United Kingdom,Very elderly,"Starchy roots or tubers and products thereof, ...",79.018675,87.050360
3287,United Kingdom,Very elderly,"Sugar and similar, confectionery and water-bas...",20.587659,78.417266
3288,United Kingdom,Very elderly,Vegetables and vegetable products,117.874586,93.525180
3289,United Kingdom,Very elderly,Water and water-based beverages,569.570063,95.683453

In [8]:
# Display all unique age groups in the 'Population Group (L2)' column
unique_age_groups = df_grouped["Population Group (L2)"].unique()
print(unique_age_groups)

['Adolescents' 'Adults' 'Elderly' 'Other children' 'Pregnant women'
 'Very elderly' 'Toddlers' 'Infants' 'Lactating women' 'Vegetarians']

In [9]:
# Define the specific age groups to keep
age_groups_to_keep = ["Adults", "Elderly", "Very elderly"]

# Filter the DataFrame to keep only the specified age groups
df_grouped = df_grouped[df_grouped["Population Group (L2)"].isin(age_groups_to_keep)]

# Display the updated DataFrame
df_grouped

,Survey's country,Population Group (L2),Exposure hierarchy (L1),Mean,% Consumers
19,Austria,Adults,Alcoholic beverages,150.675344,51.635042
20,Austria,Adults,Animal and vegetable fats and oils and primary...,14.828626,93.903916
21,Austria,Adults,"Coffee, cocoa, tea and infusions",494.853665,92.854259
22,Austria,Adults,Composite dishes,137.545469,53.572870
23,Austria,Adults,Eggs and egg products,13.767620,58.740412
...,...,...,...,...,...
3285,United Kingdom,Very elderly,"Seasoning, sauces and condiments",20.756175,74.820144
3286,United Kingdom,Very elderly,"Starchy roots or tubers and products thereof, ...",79.018675,87.050360
3287,United Kingdom,Very elderly,"Sugar and similar, confectionery and water-bas...",20.587659,78.417266
3288,United Kingdom,Very elderly,Vegetables and vegetable products,117.874586,93.525180
3289,United Kingdom,Very elderly,Water and water-based beverages,569.570063,95.683453

In [10]:
# Group by country and food category, and calculate the averages
df_final = df_grouped.groupby(
    ["Survey's country", "Exposure hierarchy (L1)"], as_index=False
).agg({
    "Mean": "mean",          # Average of Mean
    "% Consumers": "mean"    # Average of % Consumers across age groups
})

# Display the final DataFrame
df_final

,Survey's country,Exposure hierarchy (L1),Mean,% Consumers
0,Austria,Alcoholic beverages,166.516408,57.092278
1,Austria,Animal and vegetable fats and oils and primary...,17.191352,91.818718
2,Austria,"Coffee, cocoa, tea and infusions",506.164903,97.618086
3,Austria,Composite dishes,204.744410,81.539216
4,Austria,Eggs and egg products,8.795674,31.560237
...,...,...,...,...
525,United Kingdom,"Seasoning, sauces and condiments",25.282324,85.349579
526,United Kingdom,"Starchy roots or tubers and products thereof, ...",75.385594,87.944135
527,United Kingdom,"Sugar and similar, confectionery and water-bas...",19.715225,78.596410
528,United Kingdom,Vegetables and vegetable products,133.439191,95.588835
529,United Kingdom,Water and water-based beverages,681.558158,96.586832

In [11]:
# Pivot the DataFrame
df_pivot = df_final.pivot(
    index="Survey's country",  # Rows: each country
    columns="Exposure hierarchy (L1)",  # Columns: each food type
    values="Mean"  # Values: the mean consumption
)

# Reset the index to turn the country column back into a normal column
df_pivot = df_pivot.reset_index()

# Display the pivoted DataFrame
df_pivot

Exposure hierarchy (L1),Survey's country,Alcoholic beverages,"Amphibians, reptiles, and terrestrial invertebrates",Animal and vegetable fats and oils and primary derivatives thereof,"Coffee, cocoa, tea and infusions",Composite dishes,Eggs and egg products,Fish and seafood,Food products for young population,Fruit and fruit products,...,"Major isolated ingredients, additives, flavours, baking and processing aids",Meat and meat products,Milk and dairy products,Other ingredients,"Products for non-standard diets, food imitates and food supplements","Seasoning, sauces and condiments","Starchy roots or tubers and products thereof, sugar plants","Sugar and similar, confectionery and water-based sweet desserts",Vegetables and vegetable products,Water and water-based beverages
0,Austria,166.516408,NaN,17.191352,506.164903,204.744410,8.795674,20.834679,NaN,151.713658,...,0.185394,88.061634,159.150887,NaN,4.772915,24.045274,25.532152,12.393363,106.405959,1147.504358
1,Belgium,176.182765,0.138166,38.234566,485.317295,139.873394,9.326120,25.907912,0.181111,149.255072,...,0.082624,119.521214,166.454963,NaN,6.447024,25.630590,106.421072,19.649948,134.006988,728.649289
2,Bosnia and Herzegovina,53.757918,NaN,18.483524,223.446471,4.099412,43.402229,14.369406,0.967059,130.164118,...,0.095088,151.848653,160.424712,NaN,0.712165,10.472947,68.152053,10.943894,148.532729,1157.601324
3,Croatia,104.608156,0.200416,20.455774,253.494776,2.102810,18.856405,21.400130,1.421579,169.739195,...,0.342856,138.512775,178.013741,0.014730,5.428320,11.213325,64.364645,9.852132,156.121909,974.833203
4,Cyprus,78.273638,0.009615,28.095809,164.615630,11.263452,14.164456,30.885233,0.459559,133.808601,...,0.935655,135.260535,198.019598,NaN,4.266961,5.162193,91.126593,9.250543,234.628936,1271.179959
5,Czechia,431.612281,NaN,41.214187,11.445348,60.466137,19.506432,16.383694,0.264106,124.085417,...,0.908295,182.987893,176.404565,NaN,0.385030,16.720591,87.144097,20.895504,117.230720,1426.876152
6,Denmark,321.711864,NaN,32.621097,914.687473,4.262592,18.497150,25.876676,NaN,182.637542,...,0.423584,121.068529,370.264266,NaN,0.377921,8.549827,121.559825,33.047668,147.644422,897.620148
7,Estonia,71.815056,0.009574,19.068371,462.909363,0.924319,21.818647,29.133138,0.197064,224.252590,...,1.855157,126.843189,288.458739,NaN,1.740772,6.904246,104.531538,24.935095,159.349878,785.615921
8,Finland,96.913844,0.047792,32.531320,580.567592,19.562481,15.836299,32.431042,0.131901,174.065812,...,3.527509,119.611618,414.443750,NaN,9.745016,21.724084,76.080315,20.941222,145.552879,929.047543
9,France,128.432191,0.102354,30.131722,409.726152,36.563380,17.531500,36.345468,0.445617,187.103861,...,0.316608,121.746676,225.980287,NaN,5.747914,23.177350,76.917594,17.285721,222.493113,883.467077
10,Germany,209.980484,0.035560,25.254457,790.693976,127.066161,11.235629,18.525502,NaN,210.658236,...,0.018107,97.957305,191.843042,NaN,1.846549,27.116370,51.757449,16.984964,98.405596,918.704277
11,Greece,92.315482,0.351770,36.530838,18.544471,0.884915,11.976884,31.684791,NaN,156.062049,...,0.044781,100.535485,199.892202,NaN,0.448386,10.265250,50.429035,13.998179,205.880736,493.903749
12,Hungary,70.574369,NaN,36.728944,234.372971,3.629270,23.040902,7.824991,0.275277,184.745551,...,0.564422,166.295827,247.994426,NaN,6.742876,13.083476,100.248637,25.007251,181.707954,644.742026
13,Ireland,196.182091,NaN,25.439884,601.841978,43.630847,17.956439,30.400699,0.007307,103.405335,...,0.638303,156.794811,276.339671,NaN,6.827091,20.295170,121.175089,16.997548,133.646244,512.352296
14,Italy,105.515596,0.073560,34.644765,152.205478,9.359083,18.739137,41.296143,0.158468,232.068305,...,0.335059,104.853819,194.942716,NaN,3.876397,3.094255,48.536660,17.784592,238.462798,893.414120
15,Latvia,52.637448,NaN,14.870916,454.452114,116.734517,16.208971,22.587325,NaN,127.596425,...,0.346837,162.006563,212.655380,NaN,0.860361,20.626037,107.437701,24.977547,179.150295,366.972612
16,Montenegro,58.231850,NaN,18.238857,227.960544,3.725660,39.830382,25.439909,4.365001,124.764601,...,0.063107,126.745983,224.534971,NaN,0.220207,9.647308,66.741497,10.965124,169.876881,728.627033
17,Netherlands,171.513493,0.009723,26.146255,835.112710,109.400579,12.074121,19.015256,0.121427,144.545260,...,0.186491,118.358185,343.137107,NaN,9.132902,29.294809,75.432791,25.144492,157.524970,694.036958
18,Poland,52.308600,NaN,31.753797,456.866840,0.126220,38.734444,14.999519,0.525700,101.736843,...,0.130896,124.943407,113.020365,NaN,1.308831,9.394734,94.048640,7.644009,137.412662,301.138233
19,Portugal,153.401838,0.145792,18.922567,172.778015,1.356313,13.991541,59.752376,2.420222,191.213617,...,0.801258,124.956505,224.832677,NaN,10.799679,6.018768,103.170691,16.164124,189.464625,919.466154
20,Romania,65.139945,NaN,39.327920,181.323171,48.272053,35.768989,19.616930,NaN,165.036417,...,0.394059,155.598429,156.779223,NaN,1.318719,9.921454,85.378759,11.050357,311.990459,650.648438
21,Serbia,101.586933,NaN,18.214833,291.951699,2.773877,39.444472,18.674882,3.688217,166.278925,...,0.172229,150.931998,207.536694,0.004445,0.935863,12.692300,63.040376,8.891231,227.095938,1159.135235
22,Slovenia,96.839051,NaN,17.378676,239.067601,0.397258,24.747546,15.012049,1.370451,180.175890,...,0.417052,163.239386,148.334800,NaN,3.479423,16.629190,62.936452,9.779420,152.571718,878.909864
23,Spain,102.711515,0.128555,25.476703,55.137712,7.560290,20.522872,57.764835,0.021971,204.496364,...,0.002146,115.950311,337.402092,NaN,15.574581,8.756430,51.288269,10.858566,167.292545,644.118215
24,Sweden,143.478173,0.007084,16.083209,462.855093,220.092862,18.209362,50.514049,0.017710,155.239058,...,0.313980,109.795086,317.002258,NaN,5.221282,34.019313,115.550775,12.817194,84.553756,605.786034
25,United Kingdom,196.235608,NaN,16.254384,548.037344,123.784176,14.958145,31.200603,0.001382,108.694890,...,0.231449,80.934447,254.784939,0.000031,10.301345,25.282324,75.385594,19.715225,133.439191,681.558158

In [12]:
# Identify missing values in the pivoted DataFrame
missing_values = df_pivot.isnull().sum()

# Filter to show only columns with missing values
columns_with_missing = missing_values[missing_values > 0]

# Display the columns with missing values and their counts
print(columns_with_missing)

Exposure hierarchy (L1)
Amphibians, reptiles, and terrestrial invertebrates    13
Food products for young population                      6
Other ingredients                                      23
dtype: int64

In [13]:
# Identify missing values in the pivoted DataFrame
missing_values = df_pivot.isnull().sum()

# Filter to show only columns with missing values
columns_with_missing = missing_values[missing_values > 0]

# Show all data for the columns with missing values
columns_with_missing_data = df_pivot[columns_with_missing.index]
columns_with_missing_data

Exposure hierarchy (L1),"Amphibians, reptiles, and terrestrial invertebrates",Food products for young population,Other ingredients
0,NaN,NaN,NaN
1,0.138166,0.181111,NaN
2,NaN,0.967059,NaN
3,0.200416,1.421579,0.014730
4,0.009615,0.459559,NaN
5,NaN,0.264106,NaN
6,NaN,NaN,NaN
7,0.009574,0.197064,NaN
8,0.047792,0.131901,NaN
9,0.102354,0.445617,NaN
10,0.035560,NaN,NaN
11,0.351770,NaN,NaN
12,NaN,0.275277,NaN
13,NaN,0.007307,NaN
14,0.073560,0.158468,NaN
15,NaN,NaN,NaN
16,NaN,4.365001,NaN
17,0.009723,0.121427,NaN
18,NaN,0.525700,NaN
19,0.145792,2.420222,NaN
20,NaN,NaN,NaN
21,NaN,3.688217,0.004445
22,NaN,1.370451,NaN
23,0.128555,0.021971,NaN
24,0.007084,0.017710,NaN
25,NaN,0.001382,0.000031

In [14]:
# Set missing values for 'Amphibians, reptiles, and terrestrial invertebrates' and 'Food products for young population' to 0
df_pivot['Amphibians, reptiles, and terrestrial invertebrates'] = (
    df_pivot['Amphibians, reptiles, and terrestrial invertebrates'].fillna(0)
)
df_pivot['Food products for young population'] = df_pivot['Food products for young population'].fillna(0)

# Drop the 'Other ingredients' column
df_pivot = df_pivot.drop(columns=['Other ingredients'])

# Display the updated DataFrame
df_pivot

Exposure hierarchy (L1),Survey's country,Alcoholic beverages,"Amphibians, reptiles, and terrestrial invertebrates",Animal and vegetable fats and oils and primary derivatives thereof,"Coffee, cocoa, tea and infusions",Composite dishes,Eggs and egg products,Fish and seafood,Food products for young population,Fruit and fruit products,...,"Legumes, nuts, oilseeds and spices","Major isolated ingredients, additives, flavours, baking and processing aids",Meat and meat products,Milk and dairy products,"Products for non-standard diets, food imitates and food supplements","Seasoning, sauces and condiments","Starchy roots or tubers and products thereof, sugar plants","Sugar and similar, confectionery and water-based sweet desserts",Vegetables and vegetable products,Water and water-based beverages
0,Austria,166.516408,0.000000,17.191352,506.164903,204.744410,8.795674,20.834679,0.000000,151.713658,...,8.533545,0.185394,88.061634,159.150887,4.772915,24.045274,25.532152,12.393363,106.405959,1147.504358
1,Belgium,176.182765,0.138166,38.234566,485.317295,139.873394,9.326120,25.907912,0.181111,149.255072,...,7.046268,0.082624,119.521214,166.454963,6.447024,25.630590,106.421072,19.649948,134.006988,728.649289
2,Bosnia and Herzegovina,53.757918,0.000000,18.483524,223.446471,4.099412,43.402229,14.369406,0.967059,130.164118,...,13.370076,0.095088,151.848653,160.424712,0.712165,10.472947,68.152053,10.943894,148.532729,1157.601324
3,Croatia,104.608156,0.200416,20.455774,253.494776,2.102810,18.856405,21.400130,1.421579,169.739195,...,15.318629,0.342856,138.512775,178.013741,5.428320,11.213325,64.364645,9.852132,156.121909,974.833203
4,Cyprus,78.273638,0.009615,28.095809,164.615630,11.263452,14.164456,30.885233,0.459559,133.808601,...,23.069827,0.935655,135.260535,198.019598,4.266961,5.162193,91.126593,9.250543,234.628936,1271.179959
5,Czechia,431.612281,0.000000,41.214187,11.445348,60.466137,19.506432,16.383694,0.264106,124.085417,...,9.360285,0.908295,182.987893,176.404565,0.385030,16.720591,87.144097,20.895504,117.230720,1426.876152
6,Denmark,321.711864,0.000000,32.621097,914.687473,4.262592,18.497150,25.876676,0.000000,182.637542,...,8.705850,0.423584,121.068529,370.264266,0.377921,8.549827,121.559825,33.047668,147.644422,897.620148
7,Estonia,71.815056,0.009574,19.068371,462.909363,0.924319,21.818647,29.133138,0.197064,224.252590,...,8.265563,1.855157,126.843189,288.458739,1.740772,6.904246,104.531538,24.935095,159.349878,785.615921
8,Finland,96.913844,0.047792,32.531320,580.567592,19.562481,15.836299,32.431042,0.131901,174.065812,...,9.603737,3.527509,119.611618,414.443750,9.745016,21.724084,76.080315,20.941222,145.552879,929.047543
9,France,128.432191,0.102354,30.131722,409.726152,36.563380,17.531500,36.345468,0.445617,187.103861,...,16.615162,0.316608,121.746676,225.980287,5.747914,23.177350,76.917594,17.285721,222.493113,883.467077
10,Germany,209.980484,0.035560,25.254457,790.693976,127.066161,11.235629,18.525502,0.000000,210.658236,...,8.142415,0.018107,97.957305,191.843042,1.846549,27.116370,51.757449,16.984964,98.405596,918.704277
11,Greece,92.315482,0.351770,36.530838,18.544471,0.884915,11.976884,31.684791,0.000000,156.062049,...,12.657857,0.044781,100.535485,199.892202,0.448386,10.265250,50.429035,13.998179,205.880736,493.903749
12,Hungary,70.574369,0.000000,36.728944,234.372971,3.629270,23.040902,7.824991,0.275277,184.745551,...,20.619549,0.564422,166.295827,247.994426,6.742876,13.083476,100.248637,25.007251,181.707954,644.742026
13,Ireland,196.182091,0.000000,25.439884,601.841978,43.630847,17.956439,30.400699,0.007307,103.405335,...,13.692325,0.638303,156.794811,276.339671,6.827091,20.295170,121.175089,16.997548,133.646244,512.352296
14,Italy,105.515596,0.073560,34.644765,152.205478,9.359083,18.739137,41.296143,0.158468,232.068305,...,14.450065,0.335059,104.853819,194.942716,3.876397,3.094255,48.536660,17.784592,238.462798,893.414120
15,Latvia,52.637448,0.000000,14.870916,454.452114,116.734517,16.208971,22.587325,0.000000,127.596425,...,12.749310,0.346837,162.006563,212.655380,0.860361,20.626037,107.437701,24.977547,179.150295,366.972612
16,Montenegro,58.231850,0.000000,18.238857,227.960544,3.725660,39.830382,25.439909,4.365001,124.764601,...,19.105075,0.063107,126.745983,224.534971,0.220207,9.647308,66.741497,10.965124,169.876881,728.627033
17,Netherlands,171.513493,0.009723,26.146255,835.112710,109.400579,12.074121,19.015256,0.121427,144.545260,...,14.119068,0.186491,118.358185,343.137107,9.132902,29.294809,75.432791,25.144492,157.524970,694.036958
18,Poland,52.308600,0.000000,31.753797,456.866840,0.126220,38.734444,14.999519,0.525700,101.736843,...,10.861306,0.130896,124.943407,113.020365,1.308831,9.394734,94.048640,7.644009,137.412662,301.138233
19,Portugal,153.401838,0.145792,18.922567,172.778015,1.356313,13.991541,59.752376,2.420222,191.213617,...,15.393515,0.801258,124.956505,224.832677,10.799679,6.018768,103.170691,16.164124,189.464625,919.466154
20,Romania,65.139945,0.000000,39.327920,181.323171,48.272053,35.768989,19.616930,0.000000,165.036417,...,16.535241,0.394059,155.598429,156.779223,1.318719,9.921454,85.378759,11.050357,311.990459,650.648438
21,Serbia,101.586933,0.000000,18.214833,291.951699,2.773877,39.444472,18.674882,3.688217,166.278925,...,23.938742,0.172229,150.931998,207.536694,0.935863,12.692300,63.040376,8.891231,227.095938,1159.135235
22,Slovenia,96.839051,0.000000,17.378676,239.067601,0.397258,24.747546,15.012049,1.370451,180.175890,...,14.924942,0.417052,163.239386,148.334800,3.479423,16.629190,62.936452,9.779420,152.571718,878.909864
23,Spain,102.711515,0.128555,25.476703,55.137712,7.560290,20.522872,57.764835,0.021971,204.496364,...,17.740398,0.002146,115.950311,337.402092,15.574581,8.756430,51.288269,10.858566,167.292545,644.118215
24,Sweden,143.478173,0.007084,16.083209,462.855093,220.092862,18.209362,50.514049,0.017710,155.239058,...,10.164271,0.313980,109.795086,317.002258,5.221282,34.019313,115.550775,12.817194,84.553756,605.786034
25,United Kingdom,196.235608,0.000000,16.254384,548.037344,123.784176,14.958145,31.200603,0.001382,108.694890,...,27.501502,0.231449,80.934447,254.784939,10.301345,25.282324,75.385594,19.715225,133.439191,681.558158

In [15]:
# Check for missing values in the updated DataFrame
missing_values_after_cleanup = df_pivot.isnull().sum()

# Filter to show only columns with missing values
columns_with_missing_after_cleanup = missing_values_after_cleanup[missing_values_after_cleanup > 0]

# Display columns with missing values and their counts
print(columns_with_missing_after_cleanup)

Series([], dtype: int64)